language: java

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - justmustdie@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always

services:
  - postgresql

before_install:
  - psql -c 'create database todo_test;' -U postgres